// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package analytics

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"spaudit/interfaces/web/presenters"
)

// SecurityRecommendations renders security recommendations based on analytics data
func SecurityRecommendations(analytics presenters.ListAnalytics) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"space-y-3\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if analytics.PermissionRiskLevel == "High" || analytics.UniqueAssignments > 10 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"flex items-start gap-3 p-3 bg-red-50 rounded-lg border border-red-200\"><span class=\"text-red-600 text-lg\">🚨</span><div class=\"text-sm\"><div class=\"font-medium text-red-800\">Review Unique Permissions</div><div class=\"text-red-600 mt-1\">Consider consolidating permissions to reduce complexity and security risks.</div></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if analytics.SharingLinkCount > 5 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div class=\"flex items-start gap-3 p-3 bg-amber-50 rounded-lg border border-amber-200\"><span class=\"text-amber-600 text-lg\">⚠️</span><div class=\"text-sm\"><div class=\"font-medium text-amber-800\">Monitor Sharing Links</div><div class=\"text-amber-600 mt-1\">High number of sharing links detected. Review active links and their permissions.</div></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if analytics.FullControlCount > 3 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"flex items-start gap-3 p-3 bg-orange-50 rounded-lg border border-orange-200\"><span class=\"text-orange-600 text-lg\">🔐</span><div class=\"text-sm\"><div class=\"font-medium text-orange-800\">Limit Full Control Access</div><div class=\"text-orange-600 mt-1\">Consider if all users with Full Control actually need this level of access.</div></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if analytics.PermissionRiskLevel == "Low" && analytics.SharingLinkCount == 0 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"flex items-start gap-3 p-3 bg-green-50 rounded-lg border border-green-200\"><span class=\"text-green-600 text-lg\">✅</span><div class=\"text-sm\"><div class=\"font-medium text-green-800\">Good Security Posture</div><div class=\"text-green-600 mt-1\">This list follows security best practices with minimal permission complexity.</div></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else if analytics.PermissionRiskLevel == "Low" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"flex items-start gap-3 p-3 bg-blue-50 rounded-lg border border-blue-200\"><span class=\"text-blue-600 text-lg\">ℹ️</span><div class=\"text-sm\"><div class=\"font-medium text-blue-800\">Generally Secure</div><div class=\"text-blue-600 mt-1\">This list has a low security risk profile with some sharing activity.</div></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = AnalyticsCard("Security Recommendations").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
